import './globals.css'
import ApplicationLayout from '@/components/ApplicationLayout'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@1&family=Lexend:wght@100;200;300;400;500;600;700;800&family=Raleway:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet" />
      </head>
      <body>
        <ApplicationLayout>
          {children}
        </ApplicationLayout>
      </body>
    </html>
  )
}
